from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, -1, 920, 650))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(178, 219, 255, 255));")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(0, 30, 920, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(0, 130, 920, 70))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.comComboBox = QtWidgets.QComboBox(self.tab)
        self.comComboBox.setGeometry(QtCore.QRect(390, 310, 130, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comComboBox.setFont(font)
        self.comComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comComboBox.setIconSize(QtCore.QSize(14, 14))
        self.comComboBox.setObjectName("comComboBox")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(0, 80, 911, 20))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.line_3.setFont(font)
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(0, 30, 920, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setGeometry(QtCore.QRect(0, 80, 911, 20))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(0, 110, 920, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setLineWidth(1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.dispTemp = QtWidgets.QLabel(self.tab_2)
        self.dispTemp.setGeometry(QtCore.QRect(430, 190, 281, 38))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(10)
        self.dispTemp.setFont(font)
        self.dispTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.dispTemp.setObjectName("dispTemp")
        self.getTemperature1 = QtWidgets.QPushButton(self.tab_2)
        self.getTemperature1.setGeometry(QtCore.QRect(390, 350, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(14)
        self.getTemperature1.setFont(font)
        self.getTemperature1.setObjectName("getTemperature1")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(180, 190, 260, 38))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(0, 449, 920, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(180, 250, 260, 38))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.dispHum = QtWidgets.QLabel(self.tab_2)
        self.dispHum.setGeometry(QtCore.QRect(430, 250, 281, 38))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(10)
        self.dispHum.setFont(font)
        self.dispHum.setAlignment(QtCore.Qt.AlignCenter)
        self.dispHum.setObjectName("dispHum")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(0, 490, 920, 40))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.line_2 = QtWidgets.QFrame(self.tab_3)
        self.line_2.setGeometry(QtCore.QRect(0, 80, 911, 20))
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.startAir = QtWidgets.QPushButton(self.tab_3)
        self.startAir.setGeometry(QtCore.QRect(150, 240, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.startAir.setFont(font)
        self.startAir.setObjectName("startAir")
        self.StopAir = QtWidgets.QPushButton(self.tab_3)
        self.StopAir.setGeometry(QtCore.QRect(640, 240, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.StopAir.setFont(font)
        self.StopAir.setObjectName("StopAir")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(0, 100, 920, 111))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(0, 30, 920, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(0, 360, 920, 50))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(180, 250, 260, 38))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.dispHum_2 = QtWidgets.QLabel(self.tab_4)
        self.dispHum_2.setGeometry(QtCore.QRect(430, 250, 280, 38))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(10)
        self.dispHum_2.setFont(font)
        self.dispHum_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dispHum_2.setObjectName("dispHum_2")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(180, 190, 260, 38))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.dispTemp_2 = QtWidgets.QLabel(self.tab_4)
        self.dispTemp_2.setGeometry(QtCore.QRect(430, 190, 280, 38))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(10)
        self.dispTemp_2.setFont(font)
        self.dispTemp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dispTemp_2.setObjectName("dispTemp_2")
        self.line_4 = QtWidgets.QFrame(self.tab_4)
        self.line_4.setGeometry(QtCore.QRect(0, 80, 911, 20))
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(0, 30, 920, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.saveData = QtWidgets.QPushButton(self.tab_4)
        self.saveData.setGeometry(QtCore.QRect(390, 360, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveData.setFont(font)
        self.saveData.setObjectName("saveData")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(-10, 470, 915, 40))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "COM-port"))
        self.label_2.setText(_translate("MainWindow", "Select virtual comport connection :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Connection"))
        self.label_3.setText(_translate("MainWindow", "Climate control"))
        self.label_4.setText(_translate("MainWindow", "Gather data from the room "))
        self.dispTemp.setText(_translate("MainWindow", "No info"))
        self.getTemperature1.setText(_translate("MainWindow", "Get Data"))
        self.label_5.setText(_translate("MainWindow", "Temperature:"))
        self.label_6.setText(_translate("MainWindow", "*To gain information about temperature in the room"))
        self.label_8.setText(_translate("MainWindow", "Humidity:"))
        self.dispHum.setText(_translate("MainWindow", "No info"))
        self.label_9.setText(_translate("MainWindow", "press \"Get Data\""))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Room"))
        self.startAir.setText(_translate("MainWindow", "Start"))
        self.StopAir.setText(_translate("MainWindow", "Stop"))
        self.label_7.setText(_translate("MainWindow", "Control air contitioning"))
        self.label_12.setText(_translate("MainWindow", "Air Conditioner"))
        self.label_14.setText(_translate("MainWindow", "Conditioner not working"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Conditioner"))
        self.label_10.setText(_translate("MainWindow", "Humidity:"))
        self.dispHum_2.setText(_translate("MainWindow", "No info"))
        self.label_11.setText(_translate("MainWindow", "Temperature:"))
        self.dispTemp_2.setText(_translate("MainWindow", "No info"))
        self.label_13.setText(_translate("MainWindow", "Database"))
        self.saveData.setText(_translate("MainWindow", "Save"))
        self.label_15.setText(_translate("MainWindow", "press \"Save\" to save data into database"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Database"))
